export const USER_MESSAGES = {
  VALIDATION_ERROR: 'Validation error',
  NAME_IS_REQUIRED: 'Name is required',
  NAME_MUST_BE_STRING: 'Name must be a string',
  NAME_LENGTH_MUST_BE_MORE_THAN_3: 'Name length must be more than 3',
  EMAIL_ALREADY_EXISTS: 'Email already exists',
  EMAIL_IS_REQUIRED: 'Email is required',
  EMAIL_IS_INVALID: 'Email is invalid',
  USER_NOT_FOUND: 'User not found',
  PASSWORD_IS_REQUIRED: 'Password is required',
  PASSWORD_MUST_BE_STRING: 'Password must be a string',
  PASSWORD_LENGTH_MUST_BE_MORE_THAN_6: 'Password length must be more than 6',
  PASSWORD_CONFIRMATION_DOES_NOT_MATCH_PASSWORD: 'Password confirmation does not match password',
  ACCESS_TOKEN_IS_REQUIRED: 'Access token is required',
  EMAIL_VERIFY_TOKEN_IS_REQUIRED: 'email_verify_token_is_required',
  USER_REFRESH_TOKEN_NOT_EXIST: 'user_refresh_token_not_exist',
  REFRESH_TOKEN_IS_INVALID: 'Refresh token is invalid',
  LOGOUT_SUCCESS: 'Logout success',
  EMAIL_VERIFY_SUCCESS: 'email_verify_success',
  USER_NOT_VERIFIED: 'User not verified'
}
